bank/urls.py
from django.urls import path
from . import views
app_name = 'bank'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('send/', views.send, name='send'),
    path('about_us/', views.about_us, name='about_us'),
    path('citizen/', views.citizen, name='citizen'),
    path('bank_result/', views.bank_result, name='bank_result'),
    path('send_result/', views.send_result, name='send_result'),
    path('jobs/', views.jobs, name='jobs'),
    path('get_citizenship/', views.get_citizenship, name='get_citizenship'),
    path('business_management/', views.business_management, name='business_management'),
    path('business_management/loan/', views.loan, name='loan'),
    path('business_management/fiscal_info/', views.fiscal_info, name='fiscal_info'),
    path('business_management/business_detail/<int:business_id>/', views.business_detail, name='business_detail'),
    path('business_management/delete_employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('business_management/ask_loan<int:ask_loan_id>/', views.ask_loan, name='ask_loan'),
    path('business_management/cancel_ask_loan<int:ask_loan_id>/', views.cancel_ask_loan, name='cancel_ask_loan'),
    path('businesses/', views.businesses, name='businesses'),
    path('make_order/<int:service_id>/', views.make_order, name='make_order'),
    path('laws/', views.laws, name='laws'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
    path('article/<int:article_id>', views.article, name='article')
]

gos_uslugi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank.urls')),
    path('account/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank/models.py
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.
class BankAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='bank_account')
    name = models.CharField(max_length=10, unique=True)
    balance = models.IntegerField(default=0)
    account_type = models.CharField(max_length=20, default='personal')
    def __str__(self):
        return f'{self.name}_{self.user.username}_{self.account_type}'
    class Meta:
        ordering = ['user']


class Role(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']


class Transaction(models.Model):
    sender = models.ForeignKey(BankAccount, on_delete=models.CASCADE, blank=True, null=True, related_name='account_sender')
    receiver = models.ForeignKey(BankAccount, on_delete=models.CASCADE, blank=True, null=True, related_name='account_receiver')
    amount = models.IntegerField(default=0)
    pub_time = models.DateTimeField('Publication time', default=timezone.now)
    def __str__(self):
        return f'{self.sender.name}_{self.receiver.name}_{self.amount}'



class Citizen(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='citizen')
    bank_account = models.ForeignKey(BankAccount, on_delete=models.CASCADE, blank=True, null=True, related_name='citizen')
    role = models.ManyToManyField(Role)
    discord_name = models.CharField(max_length=50, default='no')
    minecraft_name = models.CharField(max_length=16, default='no')
    country = CountryField(default="no")
    def __str__(self):
        return self.user.username
    class Meta:
        ordering = ['user']

class AskCitizenship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='ask_citizenship')
    bank_account = models.ForeignKey(BankAccount, on_delete=models.CASCADE, blank=True, null=True)
    discord_name = models.CharField(max_length=50)
    minecraft_name = models.CharField(max_length=16)
    country = CountryField(default="ru")
    def __str__(self):
        return self.user.username

class Property(models.Model):
    citizen = models.ForeignKey(Citizen, on_delete=models.CASCADE, blank=True, null=True, related_name='properties')
    property_type = models.CharField(max_length=50)
    market_price = models.IntegerField(default=0)
    name = models.CharField(max_length=100)
    description = models.TextField()
    def __str__(self):
        return f'{self.citizen.user.username} владеет {self.property_type} ({self.name}) за {self.market_price} рублей'
    class Meta:
        ordering = ['-market_price']

class JobOffer(models.Model):
    employer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_offers')
    job_name = models.CharField(max_length=50)
    salary = models.IntegerField(default=0)
    location = models.CharField(max_length=100, default='Черногорск')
    description = models.TextField()
    pub_time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f'{self.job_name}_{self.employer.username}_{self.salary}'
    class Meta:
        ordering = ['-pub_time']

class Business(models.Model):
    owner = models.ForeignKey(Citizen, on_delete=models.CASCADE, related_name='businesses')
    name = models.CharField(max_length=100)
    description = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)
    bank_account = models.ForeignKey(BankAccount, on_delete=models.CASCADE, related_name='business')
    def __str__(self):
        return f'{self.name}_{self.bank_account.name}_{self.owner.user.username}'
    class Meta:
        ordering = ['name']

class JobPosition(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='job_positions')
    name = models.CharField(max_length=100)
    description = models.TextField()
    salary = models.IntegerField(default=100)
    def __str__(self):
        return f'{self.name}'
    class Meta:
        ordering = ['-salary']

class Employee(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='employees')
    position = models.ForeignKey(JobPosition, on_delete=models.CASCADE, related_name='employees')
    worker = models.ForeignKey(Citizen, on_delete=models.CASCADE, related_name='employees')
    hire_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f'{self.worker.user.username}_{self.position.name}_{self.business.name}_{self.position.salary}'
    class Meta:
        ordering = ['-position']

class Service(models.Model):
    owner = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(max_length=500)
    price = models.IntegerField(default=0)
    SERVICE_TYPE_CHOICES = [
        ('товар', "Товар"),
        ("услуга", "Услуга"),
    ]
    service_type = models.CharField(max_length=100, default=SERVICE_TYPE_CHOICES[0][0], choices=SERVICE_TYPE_CHOICES) #подписка или разовая покупка
    def __str__(self):
        return f'{self.name}_{self.price}_{self.service_type}_{self.owner.name}'
    class Meta:
        ordering = ['-price']

class InterestRate(models.Model):
    service_type = models.CharField(max_length=50)
    rate = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.service_type}. Ставка: {self.rate}% дневных'

class AskLoan(models.Model):
    loaner = models.ForeignKey(Citizen, on_delete=models.CASCADE)
    interest_rate = models.ForeignKey(InterestRate, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    capital = models.IntegerField(default=0)
    period = models.IntegerField(default=0)
    start_date = models.DateTimeField(default=timezone.now)
    payback_date = models.DateTimeField(default= timezone.now)
    payback_sum = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.loaner.user.username}_{self.interest_rate.rate}_{self.capital}_{self.payback_sum}_{self.payback_date}'

class Loan(models.Model):
    loaner = models.ForeignKey(Citizen, on_delete=models.CASCADE, related_name='loans')
    interest_rate = models.ForeignKey(InterestRate, on_delete=models.CASCADE, related_name='loans')
    amount = models.IntegerField(default=0)
    capital = models.IntegerField(default=0)
    period = models.IntegerField(default=0)
    start_date = models.DateTimeField(default=timezone.now)
    payback_date = models.DateTimeField(default=timezone.now)
    payback_sum = models.IntegerField(default=0)
    remained_sum = models.IntegerField(default=0)
    paid_sum = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.loaner.user.username}_{self.interest_rate.rate}_{self.capital}_{self.payback_sum}_{self.payback_date}'
    class Meta:
        ordering = ['-remained_sum']

class Order(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='orders')
    amount = models.IntegerField(default=1)
    total_cost = models.IntegerField(default=0)
    buy_date = models.DateTimeField(default=timezone.now)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, default=1, related_name='orders')
    def __str__(self):
        return f'{self.service.name}_{self.amount}_{self.total_cost} рублей'
    class Meta:
        ordering = ['-buy_date']

class ExchangeRate(models.Model):
    resource = models.CharField(max_length=100)
    rate = models.IntegerField(default=1)
    last_update = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Курс {self.resource} к CHR {self.rate} рублей.'

class Car(models.Model):
    registration_plate = models.CharField(max_length=8, primary_key=True)
    owner = models.ForeignKey(Citizen, on_delete=models.CASCADE, related_name='car')
    car_model = models.OneToOneField(Property, on_delete=models.CASCADE)
    registered_by = models.ForeignKey(User, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.owner.user.username} владеет {self.car_model.name} с номером {self.registration_plate}'

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles')
    title = models.CharField(max_length=1024)
    content = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    picture = models.ImageField(upload_to='article_image/', blank=True)
    def __str__(self):
        return f'{self.title} ({self.pub_date.date()})'
    class Meta:
        ordering = ['-pub_date']

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f'{self.author} сказал в "{self.article}: {self.text}'

bank/forms.py
from django import forms
from django_countries.fields import CountryField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='Имя пользователя')
    first_name = forms.CharField(max_length=30, label="Имя")
    last_name = forms.CharField(max_length=30, label="Фамилия")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')


class SendMoney(forms.Form):
    receiver = forms.CharField(max_length=10, min_length=10, label='Код ЦБ получателя')
    amount = forms.IntegerField(min_value=100, label="Сумма")

class getCitizenShip(forms.Form):
    minecraft_username = forms.CharField(label="Ваш ник в Minecraft", min_length=3, max_length=16)
    discord_username = forms.CharField(label='Ваш ник в Discord')
    country = CountryField().formfield()

class RegisterProperty(forms.ModelForm):
    property_type = forms.CharField(label='Тип имущества (квартира, машина и тд)')
    market_price = forms.IntegerField(label="Рыночная стоимость в рублях", min_value=0)
    name = forms.CharField(label="Название")
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 20, 'placeholder': 'Описание объекта'}), label='Описание')
    class Meta:
        model = Property
        fields = ('property_type', 'market_price', 'name', 'description')

class JobOfferForm(forms.ModelForm):
    job_name = forms.CharField(label='Название работы')
    salary = forms.IntegerField(min_value=0, label='Зарплата в рублях')
    location = forms.CharField(label="Расположение")
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 20, 'placeholder': 'Введите описание вакансии, что надо будет делать сотруднику и тд.'}), label="Описание работы")
    class Meta:
        model = JobOffer
        exclude = ('employer', 'pub_time',)

class CreateBusinessForm(forms.ModelForm):
    name = forms.CharField(label='Название компании')
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите описание вашего бизнеса, например, род деятельности, местоположение и целевую аудиторию.', 'rows': 5, 'cols': 20}), label="Описание")
    class Meta:
        model = Business
        exclude = ('owner', 'creation_date', 'bank_account')

class CreateJobPosition(forms.ModelForm):
    name = forms.CharField(label="Название должности")
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите описание должности, требования и обязанности и тд.', 'rows': 5, 'cols': 20}), label="Описание")
    salary = forms.IntegerField(min_value=100, label='Зарплата в рублях за день')
    class Meta:
        model = JobPosition
        exclude = ('business',)

class CreateEmployee(forms.ModelForm):
    position = forms.ModelChoiceField(label="Должность", queryset=JobPosition.objects.all()) #Надо как-то найти бизнес_айди
    worker = forms.ModelChoiceField(label="Имя сотрудника", queryset=Citizen.objects.all())

    class Meta:
        model = Employee
        exclude = ('business', 'hire_date')

class AskLoanForm(forms.ModelForm):
    interest_rate = forms.ModelChoiceField(queryset=InterestRate.objects.all(), label="Тип займа")
    amount = forms.IntegerField(min_value=100, label="Сумма в рублях")
    period = forms.IntegerField(min_value=1, label="Срок выплаты в днях")
    class Meta:
        model = AskLoan
        exclude = ('loaner', 'capital', 'start_date', 'payback_date', 'payback_sum')

class CreateService(forms.ModelForm):
    name = forms.CharField(label="Название")
    price = forms.IntegerField(min_value=10, label="Цена в рублях")
    service_type = forms.ChoiceField(label="Товар или услуга", choices=[('товар', "Товар"),("услуга", "Услуга")])
    class Meta:
        model = Service
        exclude = ('owner',)

class MakeOrder(forms.ModelForm):
    amount = forms.IntegerField(min_value=1, label="Количество")
    class Meta:
        model = Order
        fields = ('amount',)

class RegisterCarForm(forms.ModelForm):
    owner = forms.ModelChoiceField(queryset=Citizen.objects.all(), label="Владелец")
    car_model = forms.ModelChoiceField(queryset=Property.objects.all(), label="Модель авто")
    class Meta:
        model = Car
        fields = ('owner', 'car_model')

class CreateArticleForm(forms.ModelForm):
    title = forms.CharField(label='Заголовок')
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите текст статьи', 'cols': 30}), label="Текст статьи")
    picture = forms.ImageField(label='Фото')
    class Meta:
        model = Article
        exclude = ('author', 'pub_date')
class CreateComment(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите ваш комментарий', 'cols': 30, 'rows': 3}), label="Комментарий")
    class Meta:
        model = Comment
        fields = ('text',)

bank/templates/bank/article.html
<!DOCTYPE html>
{% extends 'bank/base.html' %}
{% block page_title %}{{ article.title }}{% endblock %}
{% block body_content %}
    <div class="">
        <h1>{{ article.title }}</h1>
        <p style="line-height: 16px; font-size: 13px">Автор: <span class="text-primary">{{ article.author.username }}</span>. Дата публикации: {{ article.pub_date }}</p>
        {% if article.picture %}
            <img src="{{ article.picture.url }}" class="img-responsive" style="display: block; margin-left: auto; margin-right: auto; width: 100%">
        {% endif %}
        <p style="line-height: 30px; font-size: 18px">{{ article.content }}</p>
    </div>
    <div id="comment-section" class="jumbotron bg-info">
        <h5>Оставить комментарий</h5>
        <form method="post">
            {% csrf_token %}
            <h6>{{ form_comment.as_p }}</h6>
            <input value="Опубликовать" type="submit" class="btn btn-success">
        </form>
        <h5>Другие комментарии:</h5>
        {% for comment in article.comments.all %}
            <div class="jumbotron bg-warning">
                <p style="font-size: 13px; line-height: 21px; font-family: system-ui"><span class="text-primary">{{ comment.author.username }}</span> <span class="text-secondary">({{ comment.pub_date }})</span></p>
                <p style="font-size: 16px; line-height: 24px; font-family: system-ui">{{ comment.text }}</p>
            </div>
            {% empty %}
                <h6>Пока что нет комментариев</h6>
        {% endfor %}
    </div>
    <div class="jumbotron">
        <h4>Новости Черноруси:</h4>
        <ul class="list-group">
            {% for element in article_list %}
                <li class="list-group-item"><a style="text-decoration: none;" href="{% url 'bank:article' element.id%}">{{ element.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

bank/templates/bank/ask_loan.html
<!DOCTYPE html>
{% extends 'bank/base.html' %}
{% block page_title %}Заявка на займ{% endblock %}
{% block body_content %}
    {% load static %}
    <h1>Вы успешно оформили заявку на получение займа, в ближайшее время заявка будет рассмотрена!</h1>
    <div class="jumbotron">
        <h2>Заявка на кредит</h2>
        <h3>Тип кредита: {{ ask_loan.interest_rate }}.</h3>
        <h3>Сумма: {{ ask_loan.amount }} <img style="height: 27px" class="align-top" src="{% static 'bank/img/чернорусский рубль.png' %}">.</h3>
        <h3>Срок: {{ ask_loan.period }} дней.</h3>
        <h3>Сумма возврата: {{ ask_loan.payback_sum }} <img style="height: 27px" class="align-top" src="{% static 'bank/img/чернорусский рубль.png' %}">.</h3>
        <h3>Дата оформления: {{ ask_loan.start_date }}</h3>
        <h3>Дата полного возврата: {{ ask_loan.payback_date }}</h3>
        <h2>Вас устраивают условия?</h2>
        <a class="btn btn-lg btn-success" href="{% url 'bank:business_management' %}">Да</a>
        <a class="btn btn-lg btn-danger m-3" href="{% url 'bank:cancel_ask_loan' ask_loan.id %}">Нет</a>
    </div>
{% endblock %}

bank/templates/bank/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>ГосУслуги | {% block page_title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'bank/img/favicon.ico' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
    <link href="{% static 'bank/style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bank:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bank:send' %}">ЦБ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bank:about_us' %}">О нас</a>
                </li>
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'bank:citizen' %}">Портал Гражданина</a>
                </li>
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'bank:jobs' %}">Работа</a>
                </li>
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'bank:businesses' %}">Бизнесы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bank:laws' %}">Законы</a>
                </li>
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                    <li class="nav-item">{
                        <a class="btn btn-primary mx-3" href="{% url 'bank:profile'%}">{{ user.get_username }}</a></li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn-primary mx-3" href="{% url 'login'%}?next={{request.path}}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'bank:register'%}?next={{request.path}}">Регистрация</a>
                    </li>
                {% endif %}
            </div>
        </div>
</nav>
{% block extra_nav %}
{% endblock %}
<div class="container mt-3">
{% if user.is_authenticated %}
{% block body_content %}
{% endblock %}
{% else %}
<h1>Войдите в аккаунт для дальнейшего использования</h1>
{% endif %}
</div>
</body>
</html>

bank/templates/bank/business_management.html
<!DOCTYPE html>
{% extends 'bank/base.html' %}
{% block page_title %}Управление бизнесом{% endblock %}
{% block extra_nav %}
<nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:business_management' %}">Панель управления</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:loan' %}">Займ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:fiscal_info' %}">Налоги</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}
{% block body_content %}
    {% load static %}
    <h1>Панель управления бизнесом</h1>
    {% if has_business %}
        <h2>Ваши бизнесы:</h2>
        {% for business in businesses %}
            <div class="jumbotron">
                <h3>{{ forloop.counter }}. <a href="{% url 'bank:business_detail' business.id %}">{{ business.name }}</a>: баланс - {{ business.bank_account.balance }} <img style="height: 27px" class="align-top" src="{% static 'bank/img/чернорусский рубль.png' %}">.</h3>
            </div>
        {% endfor %}
    {% endif %}
    <hr>
    <form method="post" class="jumbotron">
        <h2>Форма создания бизнеса</h2>
        <h5 class="text-secondary">Стоимость открытия нового бизнеса составляет 1000 рублей, который пойдут на ваш корпоративный счёт.</h5>
        {% csrf_token %}
        {% if has_bank %}
            {% if has_citizenship %}
                <h3>{{ form.as_p }}</h3>
                {% if not_enough_money %}
                    <h4 class="text-danger">У вас недостаточно средств для открытия бизнеса!</h4>
                {% endif %}
            {% else %}
                <h3 class="text-danger">Сначала получите гражданство в Черноруси! Нажми <a href="{% url 'bank:citizen' %}">сюда</a></h3>
            {% endif %}
        {% else %}
            <h3 class="text-danger">Создайте сначала банковский счёт! Нажми <a href="{% url 'bank:profile' user.id%}">сюда</a></h3>
        {% endif %}
        <input class="btn btn-lg btn-success" type="submit" value="Создать">
    </form>
{% endblock %}

bank/templates/bank/fiscal_info.html
<!DOCTYPE html>
{% extends 'bank/base.html' %}
{% block page_title %}Налоги{% endblock %}
{% block extra_nav %}
<nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:business_management' %}">Панель управления</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:loan' %}">Займ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:fiscal_info' %}">Налоги</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}
{% block body_content %}
    <h1>Налоговая система Черноруси</h1>
    <h2 class="text-secondary">В этой статье будут описаны основные налоги и законы, связанные с ними.</h2>
    <div class="jumbotron">
        <h3>В основном налоги делятся на несколько типов: налог на прибыль и налог на зарплаты. В отличие от буржуйских стран, налоги у нас низкие, чтобы вы могли обеспечить приятные цены для граждан Черноруси.</h3>
        <h5><table class="table">
            <thead>
                <tr>
                    <th>Тип налога</th>
                    <th>Размер</th>
                    <th>Наказание в случае неуплаты или занижения</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Налог на прибыль (оплачивается от любого поступления на счёт фирмы)</td>
                    <td>10% от выручки</td>
                    <td>Штраф в размере x2 от общей неуплаты или срок в тюрьме</td>
                </tr>
                <tr>
                    <td>Подоходный налог на сотрудников</td>
                    <td>5% от зарплаты</td>
                    <td>Штраф в размере x10 от общей неуплаты или срок в тюрьме</td>
                </tr>
            </tbody>
        </table></h5>
    </div>
{% endblock %}

bank/templates/bank/loan.html
<!DOCTYPE html>
{% extends 'bank/base.html' %}
{% block page_title %}Займ{% endblock %}
{% block extra_nav %}
<nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:business_management' %}">Панель управления</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:loan' %}">Займ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:fiscal_info' %}">Налоги</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}
{% block body_content %}
    <h1>Банковские займы</h1>
    <h2 class="text-secondary">Тут вы можете оформить займ для различных целей.</h2>
    <div class="jumbotron">
        <h2>Оформление займа</h2>
        <form method="post">
            {% csrf_token %}
            <h3>{{ form.interest_rate.label_tag }} {{ form.interest_rate }}</h3>
            <h3>{{ form.amount.label_tag }} {{ form.amount }}</h3>
            <h3>{{ form.period.label_tag }} {{ form.period }}</h3>
            <input type="submit" class="btn btn-lg btn-success" value="Подать заявку">
        </form>
    </div>
    <h2>Ваши займы:</h2>
    {% for loan in loan_list %}
        <div class="jumbotron bg-dark text-light">
            <h3>Тип кредита: {{ loan.interest_rate }}.</h3>
            <h3>Вы взяли {{ loan.amount }} рублей {{ loan.start_date }}.</h3>
            <h3>В итоге вам надо выплатить {{ loan.payback_sum }} рублей {{ loan.payback_date }}.</h3>
            <h3>На данный момент вы уже выплатили {{ loan.paid_sum }} рублей, а осталось выплатить {{ loan.remained_sum }} рублей.</h3>
        </div>
    {% endfor %}
{% endblock %}